config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'sessions/new'
  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required


  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_url unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'ログインしました'
    else
      redner :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email,:password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = current_user.tasks
  end

  def show
    @task = current_user.tasks.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)
    task.save!
    redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
  end

  def edit
    @task = current_user.tasks.find(params[:id])
  end

  def update
    task = current_user.tasks.find(params[:id])
    task.update!(task_params)
    redirect_to tasks_url, notice: "タスク「#{task.name}」を更新しました。"
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_url, notice: "タスク「#{task.name}」を削除しました。"
  end


  private

  def task_params
    params.require(:task).permit(:name,:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      |Taskleaf
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' 
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload' 

  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Taskleaf

      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item = link_to 'タスク一覧', tasks_path, class: 'nav-link'
          li.nav-item = link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item = link_to 'ログイン', login_path, class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success = flash.notice
    = yield 
 

app/views/tasks/edit.html.slim
h1 タスクの編集
.nav.justify-content-end
  = link_to '一覧',tasks_path, class: 'nav-link'

= form_with model: @task, locale: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, row: 5, class: 'form-control', id: 'task_description'
  = f.submit nil, class: 'btn btn-primary'
  

app/views/tasks/index.html.slim
h1 タスク一覧
= link_to '新規登録', new_task_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Task.human_attribute_name(:name)
      th= Task.human_attribute_name(:created_at)
      th
      th
    tbody
    - @tasks.each do |task|
      tr
        td = link_to task.name, task
        td = task.created_at
        td = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
        td = link_to '削除', task, method: :delete, data: {confirm: "タスク#{task.name}を削除します。よろしいですか？"},class: 'btn btn-danger'

app/views/tasks/new.html.slim
h1 タスクの新規登録
.nav.justify-content-end
  = link_to '一覧',tasks_path, class: 'nav-link'

= form_with model: @task, locale: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, row: 5, class: 'form-control', id: 'task_description'
  = f.submit nil, class: 'btn btn-primary'
  

app/views/tasks/show.html.slim
h1 Tasks#show
.nav.justify-content-end
 = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th = Task.human_attribute_name(:id)
      td = @task.id
    tr
      th = Task.human_attribute_name(:name)
      td = @task.name
    tr
      th = Task.human_attribute_name(:description)
      td = simple_format(h(@task.description),{}, sanitize: false, wrapper_tag: "div")
= link_to '編集', edit_task_path, class: 'btn btn-primary mr-3'
= link_to '削除', @task, method: :delete, data: {confirm: "タスク#{@task.name}を削除します。よろしいですか？"},class: 'btn btn-danger'
    